# Generated by Django 3.2.9 on 2021-11-21 01:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_user_avatar_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_file',
            field=models.FileField(default='avatar.svg', null=True, upload_to='images/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'svg'])]),
        ),
    ]
