# Generated by Django 3.2.9 on 2021-11-21 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_user_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='avatar_file',
            new_name='avatar',
        ),
    ]
